#!/usr/bin/env bash
# A script that retrieves and displays information about subdomains

function domain_check {
 domain_names=("www" "lb-01" "web-01" "web-02")

 for h in "${domain_names[@]}";
 do
  dig "${h}"."$1" | grep -A1 'ANSWER SECTION:' | \
  awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$h"
 done
}

function subdomain_check {
 dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
 awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

if [ $# -lt 1 ]
then
 echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
 domain_check "$1";
else
 subdomain_check "$1" "$2";
fi
