#!/usr/bin/env bash
# A bash script that transfers a file from a client to a server
# Accepts 4 parameters
# 1 is the path to the file to be transferred
# 2 is the IP of the server we want to transfer the file to
# 3 is the username scp connects with

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi