#!/usr/bin/env bash

# A bash script hat displays a list of currently running processes.
# Shows all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps auxf | grep bash