#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
# The script only displays

# username
# user id
# Home directory path for the user

myfile="/etc/passwd"
while IFS= read -r eachline
do
    echo "$eachline" | cut -d':' -f1,3,6
done < "$myfile"