#!/usr/bin/env bash

# A script that sorts the data in the apache log files
# This script groups visitors by IP and HTTP status code, and displays this data.

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr