#!/usr/bin/env bash
# a bash script that displays:

# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

myfiles=$(ls)

for h in $myfiles; do
    echo "$h" | cut -d '-' -f2
done